name = "react-shop"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"
publish = ".next/static"

[site]
bucket = ".next/static"

[pages]
account_id = "your-account-id"  # 替换为你的 Cloudflare Account ID 