name = "nest-auth-app"
main = "dist/main.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
name = "nest-auth-app-prod"
workers_dev = true

[env.staging]
name = "nest-auth-app-staging"
workers_dev = true

[site]
bucket = ".next/static"

[pages]
account_id = "your-account-id"  # 替换为你的 Cloudflare Account ID 

[build.upload]
format = "service-worker" 