name = "nextjs-edge-app"
main = "src/app/page.tsx"
compatibility_date = "2024-04-24"

[build]
command = "npm run build"

[site]
bucket = ".next"

[[routes]]
pattern = "/*"
zone_name = "your-domain.com"  # 替换为你的域名 