name = "nest-auth-app"
main = "dist/main.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[env.production]
name = "nest-auth-app-prod"
route = "api.yourdomain.com/*"

[env.staging]
name = "nest-auth-app-staging"
route = "staging-api.yourdomain.com/*"

[site]
bucket = ".next/static"

[pages]
account_id = "your-account-id"  # 替换为你的 Cloudflare Account ID 