name = "react-shop"
main = "src/app/page.tsx"
compatibility_date = "2024-03-20"

[build]
command = "npm run build"
publish = ".next"

[build.upload]
format = "service-worker"

[site]
bucket = ".next"

[[routes]]
pattern = "/*"
zone_name = "your-domain.com"  # 替换为你的域名 